version: "3.8"

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  environment:
    SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@db:5432/postgres
  command: make run
  depends_on:
    db:
      condition: service_healthy

services:
  web_app:
    <<: *app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  migrate:
    <<: *app
    command: make migrate

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: